- name: playbook to install CoRR
  hosts: all
  vars:
    local_path: "{{ lookup('env', 'HOME') }}"
    anaconda_path: "{{ local_path }}/anaconda"
    default_corr_path: "{{ local_path }}/corr"
    corr_env: corr
    corr_version: master
    corr_repo: usnistgov/corr
    remote_user: "{{ lookup('env', 'USER') }}"
    conda: "{{ anaconda_path }}/bin/conda"
    env_path: "{{ anaconda_path }}/envs/{{ corr_env }}/bin"
    python: "{{ anaconda_path }}/envs/{{ corr_env }}/bin/python"
    access_log: "/var/log/corr-access.log"
    error_log: "/var/log/corr-error.log"
    gunicorn_config: "{{ local_path }}/.config/corr_config.py"
    socket_file: /tmp/app.sock
    app_service_name: corr
  tasks:

    - include: clone.yaml
      tags: [always]

    - include: mongo.yaml
      when: inventory_hostname in groups['db']
      tags: [install]

    - include: conda.yaml
      when: >
        inventory_hostname in groups['db'] or
        inventory_hostnane in groups['api'] or
        inventory_hostnane in groups['cloud']
      tags: [install]

    - include: corrdb.yaml
      when: >
        inventory_hostname in groups['db'] or
        inventory_hostnane in groups['api'] or
        inventory_hostnane in groups['cloud']
      tags: [install]

    - include: view.yaml
      when: >
        ansible_host == 'localhost' and
        inventory_hostname in groups['frontend']
      tags: [install]

    - include: serve_db.yaml
      when: inventory_hostname in groups['db']
      tags: [serve]

    - include: serve_app.yaml
      when: inventory_hostname in groups['api']
      tags: [serve]
      vars:
        app_path: "{{ corr_path }}/corr-api"
        test_path: http://0.0.0.0/api/v0.1/public/users
        mapped_port: 80

    - include: serve_app.yaml
      when: inventory_hostname in groups['cloud']
      tags: [serve]
      vars:
        app_path: "{{ corr_path }}/corr-cloud"
        test_path: http://0.0.0.0:5200/cloud/v1/public/user/home
        mapped_port: 5200

    - include: serve_frontend.yaml
      when: inventory_hostname in groups['frontend']
      tags: [serve]
