name: root
dependencies:
  - pymongo=2.8
  - nose
  - flask
  - requests
  - cssselect
  - pip:
    - mongoengine==0.8.7
    - flask-mongoengine==0.7.1
    - flask-testing
    - click
    - twill
    - lxml
